from http.server import HTTPServer, SimpleHTTPRequestHandler
from pathlib import Path
from urllib.parse import urlparse
from urllib.request import Request, urlopen
from urllib.error import URLError, HTTPError
import json
import math
import os
import re
import uuid


ROOT = Path(__file__).parent
DATA_DIR = ROOT / "data"
LESSONS_PATH = DATA_DIR / "lessons.json"
PROGRESS_PATH = DATA_DIR / "progress.json"


STOPWORDS = {
    "a", "an", "and", "are", "as", "at", "be", "by", "can", "for", "from",
    "how", "i", "in", "is", "it", "of", "on", "or", "that", "the", "this",
    "to", "what", "when", "where", "which", "why", "with", "you", "your",
}


def load_json(path, fallback):
    if not path.exists():
        return fallback
    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


def save_json(path, value):
    path.parent.mkdir(exist_ok=True)
    with path.open("w", encoding="utf-8") as file:
        json.dump(value, file, indent=2)


def tokenize(text):
    words = re.findall(r"[a-zA-Z0-9]+", text.lower())
    return [word for word in words if word not in STOPWORDS and len(word) > 1]


def cosine_similarity(query_tokens, document_tokens):
    query_counts = {}
    doc_counts = {}
    for token in query_tokens:
        query_counts[token] = query_counts.get(token, 0) + 1
    for token in document_tokens:
        doc_counts[token] = doc_counts.get(token, 0) + 1

    common = set(query_counts) & set(doc_counts)
    dot = sum(query_counts[token] * doc_counts[token] for token in common)
    query_norm = math.sqrt(sum(value * value for value in query_counts.values()))
    doc_norm = math.sqrt(sum(value * value for value in doc_counts.values()))
    if query_norm == 0 or doc_norm == 0:
        return 0
    return dot / (query_norm * doc_norm)


class TutorEngine:
    def __init__(self):
        self.lessons = load_json(LESSONS_PATH, {"lessons": []})["lessons"]
        self.progress = load_json(PROGRESS_PATH, {})
        self.last_llm_error = ""

    def lesson_index(self):
        return [
            {
                "id": lesson["id"],
                "subject": lesson["subject"],
                "title": lesson["title"],
                "level": lesson["level"],
                "summary": lesson["summary"],
            }
            for lesson in self.lessons
        ]

    def subjects(self):
        subjects = []
        for subject in sorted({lesson["subject"] for lesson in self.lessons}):
            subject_lessons = [lesson for lesson in self.lessons if lesson["subject"] == subject]
            subjects.append(
                {
                    "name": subject,
                    "lesson_count": len(subject_lessons),
                    "levels": sorted({lesson["level"] for lesson in subject_lessons}),
                }
            )
        return subjects

    def system_status(self):
        return {
            "llm_available": bool(os.environ.get("OPENAI_API_KEY", "").strip()),
            "model": os.environ.get("OPENAI_MODEL", "gpt-4o-mini"),
            "lesson_count": len(self.lessons),
            "subject_count": len({lesson["subject"] for lesson in self.lessons}),
        }

    def get_lesson(self, lesson_id):
        return next((lesson for lesson in self.lessons if lesson["id"] == lesson_id), None)

    def best_lesson_for_question(self, question, subject=None):
        query_tokens = tokenize(question)
        ranked = []
        lessons = [lesson for lesson in self.lessons if not subject or lesson["subject"] == subject]
        for lesson in lessons or self.lessons:
            search_text = " ".join(
                [
                    lesson["subject"],
                    lesson["title"],
                    lesson["summary"],
                    lesson["content"],
                    " ".join(lesson["keywords"]),
                ]
            )
            score = cosine_similarity(query_tokens, tokenize(search_text))
            ranked.append((score, lesson))
        ranked.sort(key=lambda item: item[0], reverse=True)
        return ranked[0]

    def ask(self, question, subject=None, use_llm=False):
        score, lesson = self.best_lesson_for_question(question, subject)
        matched_scope = subject or "All Subjects"
        if subject and score < 0.08:
            score, lesson = self.best_lesson_for_question(question, None)
            matched_scope = "All Subjects"
        if score < 0.08:
            general_answer = self.general_llm_answer(question, subject)
            if general_answer:
                return {
                    "type": "general",
                    "subject": subject or "General",
                    "title": "General Tutor Answer",
                    "answer": general_answer,
                    "example": "This answer was generated by the LLM because the question did not match the lesson bank.",
                    "confidence": 1,
                    "llm_used": True,
                    "matched_scope": "LLM General Knowledge",
                }
            if os.environ.get("OPENAI_API_KEY", "").strip() and self.last_llm_error:
                return {
                    "type": "fallback",
                    "answer": f"LLM request failed: {self.last_llm_error}",
                    "confidence": round(score, 2),
                }
            return {
                "type": "fallback",
                "answer": "I could not find this in the lesson bank. To answer any topic, set OPENAI_API_KEY and restart the app; then the LLM general tutor will answer broader questions.",
                "confidence": round(score, 2),
            }
        llm_answer = self.llm_answer(question, lesson) if use_llm else None
        return {
            "type": "lesson",
            "lesson_id": lesson["id"],
            "subject": lesson["subject"],
            "title": lesson["title"],
            "answer": llm_answer or lesson["content"],
            "example": lesson["example"],
            "confidence": round(score, 2),
            "llm_used": bool(llm_answer),
            "matched_scope": matched_scope,
        }

    def quiz(self, lesson_id=None, subject=None):
        lesson = self.get_lesson(lesson_id) if lesson_id else None
        if not lesson and subject:
            lesson = next((item for item in self.lessons if item["subject"] == subject), None)
        if not lesson:
            lesson = self.lessons[0]
        if not lesson:
            return None
        return {
            "lesson_id": lesson["id"],
            "lesson_title": lesson["title"],
            "question": lesson["quiz"]["question"],
        }

    def llm_answer(self, question, lesson):
        api_key = os.environ.get("OPENAI_API_KEY", "").strip()
        if not api_key:
            return None

        model = os.environ.get("OPENAI_MODEL", "gpt-4o-mini")
        endpoint = os.environ.get("OPENAI_CHAT_ENDPOINT", "https://api.openai.com/v1/chat/completions")
        prompt = (
            "You are an intelligent tutoring system. Answer in simple student-friendly language. "
            "Use the provided lesson as the source of truth, include one short example, and end with one practice question.\n\n"
            f"Subject: {lesson['subject']}\n"
            f"Lesson: {lesson['title']}\n"
            f"Lesson content: {lesson['content']}\n"
            f"Student question: {question}"
        )
        payload = {
            "model": model,
            "messages": [
                {"role": "system", "content": "You are a patient tutor for school and college students."},
                {"role": "user", "content": prompt},
            ],
            "temperature": 0.4,
            "max_tokens": 350,
        }
        request = Request(
            endpoint,
            data=json.dumps(payload).encode("utf-8"),
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            method="POST",
        )
        try:
            with urlopen(request, timeout=20) as response:
                data = json.loads(response.read().decode("utf-8"))
                self.last_llm_error = ""
                return data["choices"][0]["message"]["content"].strip()
        except HTTPError as error:
            self.last_llm_error = f"HTTP {error.code}. Check API key, billing, model access, or rate limits."
            return None
        except URLError:
            self.last_llm_error = "Network error. Check internet connection."
            return None
        except (KeyError, TimeoutError, json.JSONDecodeError):
            self.last_llm_error = "Unexpected LLM response. Check model and endpoint settings."
            return None

    def general_llm_answer(self, question, subject=None):
        api_key = os.environ.get("OPENAI_API_KEY", "").strip()
        if not api_key:
            return None

        model = os.environ.get("OPENAI_MODEL", "gpt-4o-mini")
        endpoint = os.environ.get("OPENAI_CHAT_ENDPOINT", "https://api.openai.com/v1/chat/completions")
        prompt = (
            "You are a helpful academic tutor. Answer the student's question clearly and accurately. "
            "Use simple language, include steps when useful, and keep the answer suitable for a school or college project demo.\n\n"
            f"Selected subject: {subject or 'General'}\n"
            f"Student question: {question}"
        )
        payload = {
            "model": model,
            "messages": [
                {"role": "system", "content": "You are a patient multi-subject tutor."},
                {"role": "user", "content": prompt},
            ],
            "temperature": 0.4,
            "max_tokens": 450,
        }
        request = Request(
            endpoint,
            data=json.dumps(payload).encode("utf-8"),
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            method="POST",
        )
        try:
            with urlopen(request, timeout=25) as response:
                data = json.loads(response.read().decode("utf-8"))
                self.last_llm_error = ""
                return data["choices"][0]["message"]["content"].strip()
        except HTTPError as error:
            self.last_llm_error = f"HTTP {error.code}. Check API key, billing, model access, or rate limits."
            return None
        except URLError:
            self.last_llm_error = "Network error. Check internet connection."
            return None
        except (KeyError, TimeoutError, json.JSONDecodeError):
            self.last_llm_error = "Unexpected LLM response. Check model and endpoint settings."
            return None

    def evaluate(self, lesson_id, answer, student_id):
        lesson = self.get_lesson(lesson_id)
        if not lesson:
            return {"error": "Lesson not found."}

        expected_tokens = set(tokenize(lesson["quiz"]["expected_answer"]))
        answer_tokens = set(tokenize(answer))
        matched = sorted(expected_tokens & answer_tokens)
        missing = sorted(expected_tokens - answer_tokens)
        score = len(matched) / max(len(expected_tokens), 1)

        if score >= 0.75:
            feedback = "Excellent. Your answer covers the main idea clearly."
            mastery = "Strong"
        elif score >= 0.45:
            feedback = "Good start. Add the missing concepts to make the answer stronger."
            mastery = "Developing"
        else:
            feedback = "Review the lesson again, then try to explain the idea in your own words."
            mastery = "Needs practice"

        self.record_progress(student_id, lesson_id, round(score * 100), mastery)
        return {
            "score": round(score * 100),
            "mastery": mastery,
            "feedback": feedback,
            "matched_keywords": matched,
            "missing_keywords": missing[:6],
            "model_answer": lesson["quiz"]["expected_answer"],
        }

    def record_progress(self, student_id, lesson_id, score, mastery):
        if not student_id:
            student_id = "guest"
        attempts = self.progress.setdefault(student_id, [])
        attempts.append({"lesson_id": lesson_id, "score": score, "mastery": mastery})
        save_json(PROGRESS_PATH, self.progress)

    def student_progress(self, student_id):
        attempts = self.progress.get(student_id or "guest", [])
        completed = len(attempts)
        average = round(sum(item["score"] for item in attempts) / completed, 1) if completed else 0
        return {"attempts": attempts[-8:], "completed": completed, "average_score": average}


class TutorRequestHandler(SimpleHTTPRequestHandler):
    engine = TutorEngine()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(ROOT), **kwargs)

    def do_GET(self):
        parsed = urlparse(self.path)
        if parsed.path == "/":
            self.path = "/templates/index.html"
            return super().do_GET()
        if parsed.path == "/api/lessons":
            return self.send_json({"lessons": self.engine.lesson_index()})
        if parsed.path == "/api/subjects":
            return self.send_json({"subjects": self.engine.subjects()})
        if parsed.path == "/api/status":
            return self.send_json(self.engine.system_status())
        if parsed.path.startswith("/api/progress/"):
            student_id = parsed.path.rsplit("/", 1)[-1]
            return self.send_json(self.engine.student_progress(student_id))
        return super().do_GET()

    def do_POST(self):
        parsed = urlparse(self.path)
        payload = self.read_json()
        if parsed.path == "/api/ask":
            return self.send_json(
                self.engine.ask(
                    payload.get("question", ""),
                    payload.get("subject") or None,
                    bool(payload.get("use_llm")),
                )
            )
        if parsed.path == "/api/quiz":
            return self.send_json(self.engine.quiz(payload.get("lesson_id"), payload.get("subject") or None))
        if parsed.path == "/api/evaluate":
            result = self.engine.evaluate(
                payload.get("lesson_id", ""),
                payload.get("answer", ""),
                payload.get("student_id", "guest"),
            )
            return self.send_json(result, status=400 if "error" in result else 200)
        self.send_error(404, "API endpoint not found")

    def read_json(self):
        content_length = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(content_length).decode("utf-8")
        return json.loads(body or "{}")

    def send_json(self, value, status=200):
        body = json.dumps(value).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)


def main():
    host = "127.0.0.1"
    port = 8000
    print(f"AI-Based Intelligent Tutoring System running at http://{host}:{port}")
    print(f"Session id example: {uuid.uuid4().hex[:8]}")
    HTTPServer((host, port), TutorRequestHandler).serve_forever()


if __name__ == "__main__":
    main()
